apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/batidodecoco/k8s-argocd.git
    targetRevision: HEAD
    path: deployment/base
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-argocd # Namespace for the application

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true