apiVersion: v1
kind: Service
metadata:
  name: k8s-argocd-service
  labels:
    app.kubernetes.io/name: k8s-argocd-service
spec:
  selector:
    app.kubernetes.io/name: k8s-argocd-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 3005
      targetPort: 80