apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-argocd-deployment
  labels:
    app.kubernetes.io/name: k8s-argocd-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-argocd

  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-argocd

    spec:
      containers:
        - name: k8s-argocd-app
          image: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd:1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
      imagePullSecrets:
        - name: us-east-1-ecr-registry