apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: k8s-argocd-app
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd
  newTag: 8adb5986799cf5ffe8fcb434e4f0cb64dce3f1ab
