apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd
  newTag: ea4eeea9d12eb5137b0df77d347dffe48a3ab29e
