apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd
  newTag: 89b26258a22b584443cf9d59910e402c979b7989
