apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd:1.1.0
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/k8s-argocd
  newTag: 1.2.0
